# Generated by Django 2.0.7 on 2019-11-20 01:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('data_urodzenia', models.DateField(blank=True, null=True)),
                ('data_smierci', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['imie', 'nazwisko'],
            },
        ),
        migrations.CreateModel(
            name='Egzemplarz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unikatowe ID egzemplarza książki.', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('W', 'Wypożyczona'), ('D', 'Dostepna'), ('R', 'Zarezerwowana')], default='D', help_text='Wprowadź status ksiazki', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text='Wprowadź gatunek literacki.', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(help_text='Wprowadź tytuł książki.', max_length=150)),
                ('summary', models.TextField(help_text='Krótkie streszczenie', max_length=1000)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LaBiblioteca.Autor')),
                ('gatunek', models.ManyToManyField(help_text='Wybierz gatunek', to='LaBiblioteca.Gatunek')),
            ],
        ),
        migrations.AddField(
            model_name='egzemplarz',
            name='ksiazka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LaBiblioteca.Ksiazka'),
        ),
    ]
