# Generated by Django 2.0.7 on 2019-11-20 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaBiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ksiazka',
            old_name='summary',
            new_name='streszczenie',
        ),
    ]
