# Generated by Django 2.2.7 on 2019-11-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('LaBiblioteca', '0002_auto_20191120_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='egzemplarz',
            name='data_zwrotu',
            field=models.DateField(blank=True, null=True),
        ),
    ]
